services:
  app:
    build: .
    container_name: golang_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: article
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
